[package]
name = "platonic"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A CAD kernel"
readme = "README.md"
repository = "https://github.com/davefol/Platonic"
exclude = ["resources/test/*"]

[dependencies]
